[[inbounds]]
type = "unix_socket"
tag = "input"
path = "/tmp/mtproxy.sock"
mode = "line"

[inbounds.parser]
type = "csv"
columns = [
  { name = "id", type = "int" },
  { name = "timestamp", type = "datetime" },
  { name = "temperature.gpu", type = "float"}
]

[[outbounds]]
type = "prometheus"
tag = "prometheus"
address = "env:PROMETHEUS_ADDRESS"

[[pipes]]
inbounds = ["input"]
outbounds = []
stages = []
