[[inbounds]]
type = "unix_socket"
tag = "input"
path = "/tmp/mtproxy.sock"
mode = "line"
protocol = "input"

[[outbounds]]
type = "prometheus"
tag = "prometheus"
address = "PROMETHEUS_ADDRESS"

[[protocols]]
tag = "input"
type = "csv"
has_header = true
fields = [
  { name = "id", type = "int" },
  { name = "timestamp", type = "datetime" },
  { name = "utilization.gpu", type = "float"}
]
