[[inbounds]]
type = "unix_socket"
path = "/tmp/mtproxy.sock"
protocol = "csv"

[[inbounds]]
tag = "unix_socket2"
type = "unix_socket"
path = "/tmp/mtproxy2.sock"
protocol = "csv"

[[outbounds]]
type = "stdio"
inbounds = ["pipe:timeseries"]

[[pipes]]
type = "timeseries"
inbounds = ["inbound:unix_socket", "inbound:unix_socket2"]
values = ["utilization.gpu"]
labels = ["id"]
timestamp = "timestamp"

[[protocols]]
type = "csv"
has_header = true
fields = [
  { name = "id", type = "int" },
  { name = "timestamp", type = "datetime" },
  { name = "utilization.gpu", type = "float"}
]
