[[inbounds]]
type = "unix_socket"
tag = "input"
path = "/tmp/mtproxy.sock"
mode = "line"

[inbounds.parser]
type = "csv"
columns = [
  { name = "id", type = "number" },
  { name = "timestamp", type = "datetime" },
]

[[pipes]]
inbounds = ["input"]
outbounds = []
stages = []
