[[inbounds]]
type = "unix_socket"
path = "/tmp/mtproxy.sock"
mode = "line"
protocol = "csv"

[[outbounds]]
type = "stdout"
inbounds = ["pipe:timeseries"]

[[pipes]]
type = "timeseries"
data_inbounds = ["inbound:unix_socket"]
values = ["utilization.gpu"]
labels = ["id"]
timestamp = "timestamp"

[[protocols]]
type = "csv"
has_header = true
fields = [
  { name = "id", type = "int" },
  { name = "timestamp", type = "datetime" },
  { name = "utilization.gpu", type = "float"}
]
