name: Build and Compress

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: void
            asset_name: void-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: void
            asset_name: void-linux-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools for ARM (Linux)
      if: contains(matrix.target, 'aarch64') && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
        # 为ring库安装必要的依赖
        sudo apt-get install -y libssl-dev pkg-config clang llvm-dev libclang-dev
        # 正确设置交叉编译环境变量
        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

    - name: Configure Tokio Unstable Features
      shell: bash
      run: |
        mkdir -p .cargo
        echo '[build]' > .cargo/config.toml
        echo 'rustflags = ["--cfg", "tokio_unstable"]' >> .cargo/config.toml

        # 为ring库添加特定配置
        if [[ "${{ contains(matrix.target, 'aarch64') && matrix.os == 'ubuntu-latest' }}" == "true" ]]; then
          echo '[target.aarch64-unknown-linux-gnu]' >> .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml
        fi

    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.target }}-cargo-

    - name: Build for ARM Linux
      if: contains(matrix.target, 'aarch64')
      run: |
        # 为ring库设置必要的环境变量
        export PKG_CONFIG_ALLOW_CROSS=1
        export OPENSSL_DIR=/usr

        # 使用cross进行交叉编译
        cargo install cross --git https://github.com/cross-rs/cross
        cross build --release --target ${{ matrix.target }}

    - name: Build for x86_64 Linux
      if: contains(matrix.target, 'x86_64')
      run: |
        cargo build --release --target ${{ matrix.target }}

    - name: Install UPX
      run: sudo apt-get update && sudo apt-get install -y upx

    - name: Compress Binary
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} ./${{ matrix.asset_name }}

        # 检查二进制文件是否存在且大小大于0
        if [ -s ./${{ matrix.asset_name }} ]; then
          upx -9 ./${{ matrix.asset_name }}
        else
          echo "Binary not found or empty. Skipping UPX compression."
          exit 1
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ./${{ matrix.asset_name }}
        retention-days: 7

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            void-linux-amd64/void-linux-amd64
            void-linux-arm64/void-linux-arm64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
